# Generated by Django 4.1.2 on 2022-10-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_advuser_first_name_alter_advuser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='counter',
            field=models.TextField(db_index=True, default=True, verbose_name='Счетчик'),
        ),
    ]
