# Generated by Django 4.1.2 on 2022-10-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_bb_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='counter',
            field=models.TextField(db_index=True, verbose_name='Счетчик'),
        ),
    ]
