# Generated by Django 4.1.2 on 2022-10-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_bb_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='bb',
            name='counter',
            field=models.TextField(default='0', verbose_name='Счетчик'),
        ),
        migrations.AlterField(
            model_name='additionalimage',
            name='bb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.bb', verbose_name='Заявка'),
        ),
    ]
