# Generated by Django 4.1.2 on 2022-10-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_bb_options_bb_counter_alter_additionalimage_bb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='counter',
        ),
    ]
