# Generated by Django 4.1.2 on 2022-11-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_bb_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='counter',
            field=models.IntegerField(blank=True, null=True, verbose_name='счетчик'),
        ),
    ]
