# Generated by Django 4.1.2 on 2022-11-07 17:06

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_bb_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='commented',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bb',
            name='imageses',
            field=models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name=' Доп Изображение'),
        ),
    ]
