# Generated by Django 4.1.2 on 2022-11-15 05:43

import django.core.validators
from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_advuser_username_alter_bb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='image',
            field=models.ImageField(blank=True, help_text='Максимальный объем файла не должен превышать 2 МБ', upload_to=main.utilities.get_timestamp_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='title',
            field=models.CharField(max_length=40, verbose_name='Название'),
        ),
    ]
